### ISSUE TITLE
Broken link for raw .qbtheme download on draculatheme.com/qbittorrent page

### ISSUE THREAD

**Issue by xorza** [dracula/qbittorrent#15]
![image](https://user-images.githubusercontent.com/1442523/205107825-470ba00b-5955-4558-b5da-7a5f5cf031e3.png)

![image](https://user-images.githubusercontent.com/1442523/205107873-67f635ff-0ec1-469d-83c9-2e8509a48774.png)

**Comment by JamesCarnley** [comment]
Link is to https://github.com/dracula/qbittorrent/raw/master/qbittorrent.qbtheme

Needs to be replaced with https://github.com/dracula/qbittorrent/raw/master/dracula.qbtheme

The name of the file changed from qbittorrent to dracula

**Comment by MahdiMirzade** [comment]
[The website](https://github.com/dracula/draculatheme.com) has not been updated yet, for now use the links provided in [INSTALL.md](https://github.com/dracula/qbittorrent/blob/master/INSTALL.md).
We'll need to wait until the next update for the website.

**Comment by MahdiMirzade** [comment]
It is now fixed, closing this issue.
