### ISSUE TITLE
Theme for WebUI

### ISSUE THREAD

**Issue by artemartemenko** [dracula/qbittorrent#3]
Is it possible to adapt this theme for WebUI?
The theme is very good. But lately I have been using qBittorrent on my server via web browser. The WebUI supports alternative themes, but they must be in a different format.

**Comment by MahdiMirzade** [comment]
Hi, sorry for the late reply. Also thanks for your interest in using this theme.

Regarding your request I made the WebUI theme for dracula, you can check it out [on the official repo](https://github.com/MahdiMirzade/qbittorrent), or you can chech the documentation in the [INSTALL.md](https://github.com/dracula/qbittorrent/blob/master/INSTALL.md) file in this repository to see how you can install it.

Preview for the WebUI theme:

![screenshot webui](https://user-images.githubusercontent.com/63877463/160242346-df8d7a7a-43f0-40d3-8e00-b9cdd34faba8.png)

Kind Regards, Mahdi

**Comment by bkarakashev** [comment]
It doesn't work in the WebUI qBittorrent v4.5.2 Web UI (64-bit)
The font becomes all like hieroglyphics. It is imposible to read anything
