### ISSUE TITLE
Scrollbar

### ISSUE THREAD

**Issue by ady94vasilica** [dracula/qbittorrent#5]
The scroll bar has a color that is not very visible from a greater distance, especially when there are more torrents and the bar becomes smaller. https://i.imgur.com/YDDSm6c.png

**Comment by MahdiMirzade** [comment]
This issue is now fixed by the latest theme update and re-writing the stylesheet.
Download it by [clicking here](https://github.com/dracula/qbittorrent/raw/master/dracula.qbtheme).

Reopen the issue if necessary.
