### ISSUE TITLE
PNG requests return 500 server error

### ISSUE THREAD

**Issue by alpha-tango-kilo** [dracula/qbittorrent#6]
No PNG icons from the theme are loading for me. Inspecting the requests show 500 errors. Not too sure of the cause here, but I'm inclined to believe it's not my fault as I can replicate the 500 errors doing requests on localhost (see 2nd screenshot trying to `wget` - I do run a non-standard WebUI port).

![image](https://user-images.githubusercontent.com/12728900/167265988-589ec5de-70f4-4e9c-8025-6dd4b47c31ed.png)

![image](https://user-images.githubusercontent.com/12728900/167266050-2d6993ed-c285-4512-9a8b-ac7e6d6ee7e9.png)

qBittorrent's log file doesn't show anything related, and neither do Docker's container logs.

For my setup, I'm using the [linuxserver/docker-qbittorrent](https://github.com/linuxserver/docker-qbittorrent) docker image, and I've mapped `/dracula-theme/webui` (`dracula-theme` being the repo root) to `/theme` as readonly, and then have set the alternative web UI location to be `/theme`. All files are owned by the container user / `abc` and are all `777` per the install instructions.

Apologies for the complex (though hopefully fairly easy to reproduce) setup, any pointers on where I might go from here?

**Comment by whisperua** [comment]
Same problem 
![image](https://user-images.githubusercontent.com/56673712/196824257-e889a361-5bee-40ae-ab8e-8cc089fc68f8.png)

**Comment by MahdiMirzade** [comment]
The #11 pull request should do the fix.
Will auto close if no replies till 1st Dec 2022.

**Comment by alpha-tango-kilo** [comment]
Works for me now, thanks!
